#!/usr/bin/env python3
"""Fail CI when LLVM coverage drops below a configured line-coverage floor."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


def extract_total_line(summary_text: str) -> str:
    for raw_line in summary_text.splitlines():
        line = raw_line.strip()
        if line.startswith("TOTAL"):
            return raw_line
    raise ValueError("Could not find TOTAL row in llvm-cov summary output.")


def extract_line_coverage_percent(total_line: str) -> float:
    # Typical TOTAL row contains percentages for regions, functions, and lines.
    # We gate on line coverage (third percentage entry).
    percentages = [float(value) for value in re.findall(r"(\d+(?:\.\d+)?)%", total_line)]
    if len(percentages) < 3:
        raise ValueError(
            "Unexpected TOTAL row format; expected at least 3 percentage columns "
            f"(regions/functions/lines). Row: {total_line!r}"
        )
    return percentages[2]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check llvm-cov summary TOTAL line coverage against a minimum threshold."
    )
    parser.add_argument(
        "--summary",
        required=True,
        help="Path to summary file generated by `cargo llvm-cov report --summary-only`.",
    )
    parser.add_argument(
        "--min-line-percent",
        required=True,
        type=float,
        help="Minimum allowed line coverage percentage.",
    )
    args = parser.parse_args()

    summary_path = pathlib.Path(args.summary)
    if not summary_path.exists():
        print(f"ERROR: summary file not found: {summary_path}", file=sys.stderr)
        return 2

    summary_text = summary_path.read_text(encoding="utf-8")
    total_line = extract_total_line(summary_text)
    line_percent = extract_line_coverage_percent(total_line)
    min_percent = args.min_line_percent

    print(
        f"LLVM line coverage gate: measured={line_percent:.2f}% "
        f"required>={min_percent:.2f}%"
    )

    if line_percent < min_percent:
        print("ERROR: coverage threshold not met.", file=sys.stderr)
        return 1

    print("Coverage threshold satisfied.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
