#!/usr/bin/env python3
"""Generate Coq prototype theorem module from kernel semantics artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ARTIFACT = ROOT / "artifacts" / "kernel-semantics" / "kernel_semantics_v1.json"
DEFAULT_OUT = ROOT / "artifacts" / "kernel-semantics" / "coq" / "KernelSemanticsV1.v"


def coq_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render_string_list(values: list[str]) -> str:
    if not values:
        return "[]"
    body = "; ".join(coq_string(v) for v in values)
    return f"[{body}]"


def render_obligation_profiles(profiles: list[dict[str, object]]) -> str:
    if not profiles:
        return "[]"
    lines: list[str] = ["["]
    for profile in profiles:
        fairness = profile.get("fairness")
        if fairness is None:
            fairness_expr = "None"
        else:
            fairness_expr = f"Some {render_string_list(list(fairness))}"
        lines.append("    {|")
        lines.append(f"      kind := {coq_string(str(profile['kind']))};")
        lines.append(f"      proof_engine := {coq_string(str(profile['proof_engine']))};")
        lines.append(
            "      required_obligations := "
            f"{render_string_list(list(profile['required_obligations']))};"
        )
        lines.append(
            "      requires_induction_k := "
            f"{str(bool(profile['requires_induction_k'])).lower()};"
        )
        lines.append(f"      fairness := {fairness_expr};")
        lines.append("    |};")
    lines.append("  ]")
    return "\n".join(lines)


def render_governance_profiles(profiles: list[dict[str, object]]) -> str:
    if not profiles:
        return "[]"
    lines: list[str] = ["["]
    for profile in profiles:
        lines.append("    {|")
        lines.append(f"      name := {coq_string(str(profile['name']))};")
        lines.append(f"      min_solvers := {int(profile['min_solvers'])};")
        lines.append(
            f"      require_proofs := {str(bool(profile['require_proofs'])).lower()};"
        )
        lines.append(
            "      require_proof_checker := "
            f"{str(bool(profile['require_proof_checker'])).lower()};"
        )
        lines.append(
            "      require_foundational_proof_path := "
            f"{str(bool(profile['require_foundational_proof_path'])).lower()};"
        )
        lines.append("    |};")
    lines.append("  ]")
    return "\n".join(lines)


def render_module(artifact: dict[str, object]) -> str:
    obligation_profiles = list(artifact["obligation_profiles"])
    governance_profiles = list(artifact["governance_profiles"])
    issue_codes = list(artifact["issue_codes"])
    return (
        "(* Auto-generated by .github/scripts/export_kernel_semantics_coq.py.\n"
        "   Do not edit manually; regenerate from kernel_semantics_v1.json. *)\n"
        "From Coq Require Import String List Bool Arith.\n"
        "Import ListNotations.\n"
        "Open Scope string_scope.\n\n"
        "Module TarsierKernelSemanticsV1.\n\n"
        "Record obligation_profile := {\n"
        "  kind : string;\n"
        "  proof_engine : string;\n"
        "  required_obligations : list string;\n"
        "  requires_induction_k : bool;\n"
        "  fairness : option (list string);\n"
        "}.\n\n"
        "Record governance_profile := {\n"
        "  name : string;\n"
        "  min_solvers : nat;\n"
        "  require_proofs : bool;\n"
        "  require_proof_checker : bool;\n"
        "  require_foundational_proof_path : bool;\n"
        "}.\n\n"
        "Record kernel_semantics_artifact := {\n"
        "  schema_version : nat;\n"
        "  certificate_schema_version : nat;\n"
        "  certificate_hash_domain_tag : string;\n"
        "  fail_closed : bool;\n"
        "  obligation_profiles : list obligation_profile;\n"
        "  governance_profiles : list governance_profile;\n"
        "  issue_codes : list string;\n"
        "}.\n\n"
        "Definition exported : kernel_semantics_artifact :=\n"
        "  {|\n"
        f"    schema_version := {int(artifact['schema_version'])};\n"
        f"    certificate_schema_version := {int(artifact['certificate_schema_version'])};\n"
        "    certificate_hash_domain_tag := "
        f"{coq_string(str(artifact['certificate_hash_domain_tag']))};\n"
        f"    fail_closed := {str(bool(artifact['fail_closed'])).lower()};\n"
        f"    obligation_profiles := {render_obligation_profiles(obligation_profiles)};\n"
        f"    governance_profiles := {render_governance_profiles(governance_profiles)};\n"
        f"    issue_codes := {render_string_list([str(c) for c in issue_codes])};\n"
        "  |}.\n\n"
        "Definition has_issue_codeb (artifact : kernel_semantics_artifact) (code : string) : bool :=\n"
        "  existsb (String.eqb code) artifact.(issue_codes).\n\n"
        "Definition has_profileb\n"
        "  (artifact : kernel_semantics_artifact)\n"
        "  (target_kind target_engine : string) : bool :=\n"
        "  existsb (fun profile =>\n"
        "    andb (String.eqb profile.(kind) target_kind)\n"
        "         (String.eqb profile.(proof_engine) target_engine))\n"
        "    artifact.(obligation_profiles).\n\n"
        "Definition profile_admissibilityb (artifact : kernel_semantics_artifact) : bool :=\n"
        "  forallb (fun profile =>\n"
        "    Nat.ltb 0 (List.length profile.(required_obligations)))\n"
        "    artifact.(obligation_profiles).\n\n"
        "Definition obligation_completenessb (artifact : kernel_semantics_artifact) : bool :=\n"
        "  andb (has_profileb artifact \"safety_proof\" \"kinduction\")\n"
        "    (andb (has_profileb artifact \"safety_proof\" \"pdr\")\n"
        "          (has_profileb artifact \"fair_liveness_proof\" \"pdr\")).\n\n"
        "Definition path_safety_encodingb (artifact : kernel_semantics_artifact) : bool :=\n"
        "  andb (has_issue_codeb artifact \"unsafe_path\")\n"
        "    (andb (has_issue_codeb artifact \"unsafe_proof_path\")\n"
        "          (has_issue_codeb artifact \"symlink_escape\")).\n\n"
        "Definition hash_match_encodingb (artifact : kernel_semantics_artifact) : bool :=\n"
        "  andb (has_issue_codeb artifact \"missing_bundle_hash\")\n"
        "    (andb (has_issue_codeb artifact \"missing_obligation_hash\")\n"
        "      (andb (has_issue_codeb artifact \"missing_proof_hash\")\n"
        "        (andb (has_issue_codeb artifact \"obligation_hash_mismatch\")\n"
        "          (andb (has_issue_codeb artifact \"proof_hash_mismatch\")\n"
        "                (has_issue_codeb artifact \"bundle_hash_mismatch\"))))).\n\n"
        "Definition smt_structural_sanity_encodingb (artifact : kernel_semantics_artifact) : bool :=\n"
        "  andb (has_issue_codeb artifact \"missing_assert\")\n"
        "    (andb (has_issue_codeb artifact \"check_sat_count\")\n"
        "      (andb (has_issue_codeb artifact \"exit_count\")\n"
        "        (andb (has_issue_codeb artifact \"invalid_command_order\")\n"
        "              (has_issue_codeb artifact \"disallowed_commands\")))).\n\n"
        "Definition profile_admissibility (artifact : kernel_semantics_artifact) : Prop :=\n"
        "  profile_admissibilityb artifact = true.\n\n"
        "Definition obligation_completeness (artifact : kernel_semantics_artifact) : Prop :=\n"
        "  obligation_completenessb artifact = true.\n\n"
        "Definition path_safety_encoding (artifact : kernel_semantics_artifact) : Prop :=\n"
        "  path_safety_encodingb artifact = true.\n\n"
        "Definition hash_match_encoding (artifact : kernel_semantics_artifact) : Prop :=\n"
        "  hash_match_encodingb artifact = true.\n\n"
        "Definition smt_structural_sanity_encoding (artifact : kernel_semantics_artifact) : Prop :=\n"
        "  smt_structural_sanity_encodingb artifact = true.\n\n"
        "Definition kernel_accepts (artifact : kernel_semantics_artifact) : Prop :=\n"
        "  artifact.(fail_closed) = true.\n\n"
        "Definition integrity_predicates_hold (artifact : kernel_semantics_artifact) : Prop :=\n"
        "  profile_admissibility artifact /\\\n"
        "  obligation_completeness artifact /\\\n"
        "  path_safety_encoding artifact /\\\n"
        "  hash_match_encoding artifact /\\\n"
        "  smt_structural_sanity_encoding artifact.\n\n"
        "Lemma profile_admissibility_holds : profile_admissibility exported.\n"
        "Proof. vm_compute. reflexivity. Qed.\n\n"
        "Lemma obligation_completeness_holds : obligation_completeness exported.\n"
        "Proof. vm_compute. reflexivity. Qed.\n\n"
        "Lemma path_safety_encoding_holds : path_safety_encoding exported.\n"
        "Proof. vm_compute. reflexivity. Qed.\n\n"
        "Lemma hash_match_encoding_holds : hash_match_encoding exported.\n"
        "Proof. vm_compute. reflexivity. Qed.\n\n"
        "Lemma smt_structural_sanity_encoding_holds : smt_structural_sanity_encoding exported.\n"
        "Proof. vm_compute. reflexivity. Qed.\n\n"
        "Theorem kernel_accepts_implies_integrity_predicates_hold :\n"
        "  kernel_accepts exported -> integrity_predicates_hold exported.\n"
        "Proof.\n"
        "  intro _.\n"
        "  exact (conj profile_admissibility_holds\n"
        "    (conj obligation_completeness_holds\n"
        "      (conj path_safety_encoding_holds\n"
        "        (conj hash_match_encoding_holds\n"
        "          smt_structural_sanity_encoding_holds)))).\n"
        "Qed.\n\n"
        "Definition counterexample_missing_path_code : kernel_semantics_artifact :=\n"
        "  {|\n"
        "    schema_version := exported.(schema_version);\n"
        "    certificate_schema_version := exported.(certificate_schema_version);\n"
        "    certificate_hash_domain_tag := exported.(certificate_hash_domain_tag);\n"
        "    fail_closed := exported.(fail_closed);\n"
        "    obligation_profiles := exported.(obligation_profiles);\n"
        "    governance_profiles := exported.(governance_profiles);\n"
        "    issue_codes := List.filter\n"
        "      (fun code => negb (String.eqb code \"unsafe_path\"))\n"
        "      exported.(issue_codes);\n"
        "  |}.\n\n"
        "Lemma counterexample_missing_path_code_breaks_path_safety :\n"
        "  ~ path_safety_encoding counterexample_missing_path_code.\n"
        "Proof.\n"
        "  vm_compute.\n"
        "  discriminate.\n"
        "Qed.\n\n"
        "End TarsierKernelSemanticsV1.\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    artifact = json.loads(args.artifact.read_text(encoding="utf-8"))
    rendered = render_module(artifact)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
