#!/usr/bin/env python3
"""Generate Lean prototype theorem module from kernel semantics artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ARTIFACT = ROOT / "artifacts" / "kernel-semantics" / "kernel_semantics_v1.json"
DEFAULT_OUT = (
    ROOT / "artifacts" / "kernel-semantics" / "lean" / "KernelSemanticsV1.lean"
)


def lean_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render_string_list(values: list[str]) -> str:
    if not values:
        return "[]"
    body = ", ".join(lean_string(v) for v in values)
    return f"[{body}]"


def render_obligation_profiles(profiles: list[dict[str, object]]) -> str:
    if not profiles:
        return "[]"
    lines: list[str] = ["["]
    for profile in profiles:
        fairness = profile.get("fairness")
        if fairness is None:
            fairness_expr = "none"
        else:
            fairness_expr = f"some {render_string_list(list(fairness))}"
        lines.append("    {")
        lines.append(f"      kind := {lean_string(str(profile['kind']))}")
        lines.append(f"      proofEngine := {lean_string(str(profile['proof_engine']))}")
        lines.append(
            "      requiredObligations := "
            f"{render_string_list(list(profile['required_obligations']))}"
        )
        lines.append(
            "      requiresInductionK := "
            f"{str(bool(profile['requires_induction_k'])).lower()}"
        )
        lines.append(f"      fairness := {fairness_expr}")
        lines.append("    },")
    lines.append("  ]")
    return "\n".join(lines)


def render_governance_profiles(profiles: list[dict[str, object]]) -> str:
    if not profiles:
        return "[]"
    lines: list[str] = ["["]
    for profile in profiles:
        lines.append("    {")
        lines.append(f"      name := {lean_string(str(profile['name']))}")
        lines.append(f"      minSolvers := {int(profile['min_solvers'])}")
        lines.append(
            f"      requireProofs := {str(bool(profile['require_proofs'])).lower()}"
        )
        lines.append(
            "      requireProofChecker := "
            f"{str(bool(profile['require_proof_checker'])).lower()}"
        )
        lines.append(
            "      requireFoundationalProofPath := "
            f"{str(bool(profile['require_foundational_proof_path'])).lower()}"
        )
        lines.append("    },")
    lines.append("  ]")
    return "\n".join(lines)


def render_module(artifact: dict[str, object]) -> str:
    obligation_profiles = list(artifact["obligation_profiles"])
    governance_profiles = list(artifact["governance_profiles"])
    issue_codes = list(artifact["issue_codes"])
    return (
        "/- Auto-generated by .github/scripts/export_kernel_semantics_lean.py.\n"
        "   Do not edit manually; regenerate from kernel_semantics_v1.json. -/\n\n"
        "namespace TarsierKernelSemanticsV1\n\n"
        "structure ObligationProfile where\n"
        "  kind : String\n"
        "  proofEngine : String\n"
        "  requiredObligations : List String\n"
        "  requiresInductionK : Bool\n"
        "  fairness : Option (List String)\n"
        "deriving Repr, DecidableEq\n\n"
        "structure GovernanceProfile where\n"
        "  name : String\n"
        "  minSolvers : Nat\n"
        "  requireProofs : Bool\n"
        "  requireProofChecker : Bool\n"
        "  requireFoundationalProofPath : Bool\n"
        "deriving Repr, DecidableEq\n\n"
        "structure KernelSemanticsArtifact where\n"
        "  schemaVersion : Nat\n"
        "  certificateSchemaVersion : Nat\n"
        "  certificateHashDomainTag : String\n"
        "  failClosed : Bool\n"
        "  obligationProfiles : List ObligationProfile\n"
        "  governanceProfiles : List GovernanceProfile\n"
        "  issueCodes : List String\n"
        "deriving Repr, DecidableEq\n\n"
        "def exported : KernelSemanticsArtifact := {\n"
        f"  schemaVersion := {int(artifact['schema_version'])}\n"
        f"  certificateSchemaVersion := {int(artifact['certificate_schema_version'])}\n"
        "  certificateHashDomainTag := "
        f"{lean_string(str(artifact['certificate_hash_domain_tag']))}\n"
        f"  failClosed := {str(bool(artifact['fail_closed'])).lower()}\n"
        f"  obligationProfiles := {render_obligation_profiles(obligation_profiles)}\n"
        f"  governanceProfiles := {render_governance_profiles(governance_profiles)}\n"
        f"  issueCodes := {render_string_list([str(c) for c in issue_codes])}\n"
        "}\n\n"
        "def hasIssueCodeB (artifact : KernelSemanticsArtifact) (code : String) : Bool :=\n"
        "  artifact.issueCodes.elem code\n\n"
        "def hasProfileB (artifact : KernelSemanticsArtifact) (kind proofEngine : String) : Bool :=\n"
        "  artifact.obligationProfiles.any (fun profile =>\n"
        "    profile.kind == kind && profile.proofEngine == proofEngine)\n\n"
        "def profileAdmissibilityB (artifact : KernelSemanticsArtifact) : Bool :=\n"
        "  artifact.obligationProfiles.all (fun profile =>\n"
        "    decide (profile.requiredObligations.length > 0))\n\n"
        "def obligationCompletenessB (artifact : KernelSemanticsArtifact) : Bool :=\n"
        "  hasProfileB artifact \"safety_proof\" \"kinduction\" &&\n"
        "  hasProfileB artifact \"safety_proof\" \"pdr\" &&\n"
        "  hasProfileB artifact \"fair_liveness_proof\" \"pdr\"\n\n"
        "def pathSafetyEncodingB (artifact : KernelSemanticsArtifact) : Bool :=\n"
        "  hasIssueCodeB artifact \"unsafe_path\" &&\n"
        "  hasIssueCodeB artifact \"unsafe_proof_path\" &&\n"
        "  hasIssueCodeB artifact \"symlink_escape\"\n\n"
        "def hashMatchEncodingB (artifact : KernelSemanticsArtifact) : Bool :=\n"
        "  hasIssueCodeB artifact \"missing_bundle_hash\" &&\n"
        "  hasIssueCodeB artifact \"missing_obligation_hash\" &&\n"
        "  hasIssueCodeB artifact \"missing_proof_hash\" &&\n"
        "  hasIssueCodeB artifact \"obligation_hash_mismatch\" &&\n"
        "  hasIssueCodeB artifact \"proof_hash_mismatch\" &&\n"
        "  hasIssueCodeB artifact \"bundle_hash_mismatch\"\n\n"
        "def smtStructuralSanityEncodingB (artifact : KernelSemanticsArtifact) : Bool :=\n"
        "  hasIssueCodeB artifact \"missing_assert\" &&\n"
        "  hasIssueCodeB artifact \"check_sat_count\" &&\n"
        "  hasIssueCodeB artifact \"exit_count\" &&\n"
        "  hasIssueCodeB artifact \"invalid_command_order\" &&\n"
        "  hasIssueCodeB artifact \"disallowed_commands\"\n\n"
        "def profileAdmissibility (artifact : KernelSemanticsArtifact) : Prop :=\n"
        "  profileAdmissibilityB artifact = true\n\n"
        "def obligationCompleteness (artifact : KernelSemanticsArtifact) : Prop :=\n"
        "  obligationCompletenessB artifact = true\n\n"
        "def pathSafetyEncoding (artifact : KernelSemanticsArtifact) : Prop :=\n"
        "  pathSafetyEncodingB artifact = true\n\n"
        "def hashMatchEncoding (artifact : KernelSemanticsArtifact) : Prop :=\n"
        "  hashMatchEncodingB artifact = true\n\n"
        "def smtStructuralSanityEncoding (artifact : KernelSemanticsArtifact) : Prop :=\n"
        "  smtStructuralSanityEncodingB artifact = true\n\n"
        "def kernelAccepts (artifact : KernelSemanticsArtifact) : Prop :=\n"
        "  artifact.failClosed = true\n\n"
        "def integrityPredicatesHold (artifact : KernelSemanticsArtifact) : Prop :=\n"
        "  profileAdmissibility artifact ∧\n"
        "  obligationCompleteness artifact ∧\n"
        "  pathSafetyEncoding artifact ∧\n"
        "  hashMatchEncoding artifact ∧\n"
        "  smtStructuralSanityEncoding artifact\n\n"
        "theorem profile_admissibility_holds : profileAdmissibility exported := by\n"
        "  simp [profileAdmissibility, profileAdmissibilityB, exported]\n\n"
        "theorem obligation_completeness_holds : obligationCompleteness exported := by\n"
        "  simp [obligationCompleteness, obligationCompletenessB, hasProfileB, exported]\n\n"
        "theorem path_safety_encoding_holds : pathSafetyEncoding exported := by\n"
        "  simp [pathSafetyEncoding, pathSafetyEncodingB, hasIssueCodeB, exported]\n\n"
        "theorem hash_match_encoding_holds : hashMatchEncoding exported := by\n"
        "  simp [hashMatchEncoding, hashMatchEncodingB, hasIssueCodeB, exported]\n\n"
        "theorem smt_structural_sanity_encoding_holds : smtStructuralSanityEncoding exported := by\n"
        "  simp [smtStructuralSanityEncoding, smtStructuralSanityEncodingB, hasIssueCodeB, exported]\n\n"
        "theorem kernel_accepts_implies_integrity_predicates_hold :\n"
        "    kernelAccepts exported -> integrityPredicatesHold exported := by\n"
        "  intro _\n"
        "  exact ⟨\n"
        "    profile_admissibility_holds,\n"
        "    obligation_completeness_holds,\n"
        "    path_safety_encoding_holds,\n"
        "    hash_match_encoding_holds,\n"
        "    smt_structural_sanity_encoding_holds\n"
        "  ⟩\n\n"
        "def counterexampleMissingPathCode : KernelSemanticsArtifact :=\n"
        "  { exported with issueCodes := exported.issueCodes.filter (fun code => code != \"unsafe_path\") }\n\n"
        "theorem counterexample_missing_path_code_breaks_path_safety :\n"
        "    ¬ pathSafetyEncoding counterexampleMissingPathCode := by\n"
        "  simp [pathSafetyEncoding, pathSafetyEncodingB, hasIssueCodeB,\n"
        "    counterexampleMissingPathCode, exported]\n\n"
        "end TarsierKernelSemanticsV1\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    artifact = json.loads(args.artifact.read_text(encoding="utf-8"))
    rendered = render_module(artifact)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
