name: Bug report
description: Report incorrect behavior, crashes, or unexpected verifier results.
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Provide the smallest reproducible case.
      placeholder: |
        1. Command(s) run
        2. Input `.trs` snippet or attached file
        3. Expected vs actual result
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Output
      description: Include full stdout/stderr and any JSON artifacts.
      render: shell
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Toolchain and platform details.
      placeholder: |
        rustc --version:
        cargo --version:
        OS:
        z3 --version:
        cvc5 --version:
    validations:
      required: true
