/- Auto-generated by .github/scripts/export_kernel_semantics_lean.py.
   Do not edit manually; regenerate from kernel_semantics_v1.json. -/

namespace TarsierKernelSemanticsV1

structure ObligationProfile where
  kind : String
  proofEngine : String
  requiredObligations : List String
  requiresInductionK : Bool
  fairness : Option (List String)
deriving Repr, DecidableEq

structure GovernanceProfile where
  name : String
  minSolvers : Nat
  requireProofs : Bool
  requireProofChecker : Bool
  requireFoundationalProofPath : Bool
deriving Repr, DecidableEq

structure KernelSemanticsArtifact where
  schemaVersion : Nat
  certificateSchemaVersion : Nat
  certificateHashDomainTag : String
  failClosed : Bool
  obligationProfiles : List ObligationProfile
  governanceProfiles : List GovernanceProfile
  issueCodes : List String
deriving Repr, DecidableEq

def exported : KernelSemanticsArtifact := {
  schemaVersion := 1
  certificateSchemaVersion := 2
  certificateHashDomainTag := "tarsier-certificate-v2\n"
  failClosed := true
  obligationProfiles := [
    {
      kind := "safety_proof"
      proofEngine := "kinduction"
      requiredObligations := ["base_case", "inductive_step"]
      requiresInductionK := true
      fairness := none
    },
    {
      kind := "safety_proof"
      proofEngine := "pdr"
      requiredObligations := ["init_implies_inv", "inv_and_transition_implies_inv_prime", "inv_implies_safe"]
      requiresInductionK := true
      fairness := none
    },
    {
      kind := "fair_liveness_proof"
      proofEngine := "pdr"
      requiredObligations := ["init_implies_inv", "inv_and_transition_implies_inv_prime", "inv_implies_no_fair_bad"]
      requiresInductionK := true
      fairness := some ["weak", "strong"]
    },
  ]
  governanceProfiles := [
    {
      name := "standard"
      minSolvers := 1
      requireProofs := false
      requireProofChecker := false
      requireFoundationalProofPath := false
    },
    {
      name := "reinforced"
      minSolvers := 2
      requireProofs := true
      requireProofChecker := false
      requireFoundationalProofPath := false
    },
    {
      name := "high-assurance"
      minSolvers := 2
      requireProofs := true
      requireProofChecker := true
      requireFoundationalProofPath := true
    },
  ]
  issueCodes := ["bundle_hash_mismatch", "check_sat_count", "disallowed_commands", "duplicate_obligation_file", "duplicate_obligation_name", "empty_obligations", "exit_count", "invalid_command_order", "invalid_expected", "invalid_expected_for_proof", "invalid_kind", "invalid_obligation_extension", "invalid_proof_engine", "missing_assert", "missing_bundle_hash", "missing_file", "missing_induction_k", "missing_obligation_hash", "missing_or_invalid_fairness", "missing_proof_file", "missing_proof_hash", "missing_required_obligation", "obligation_hash_mismatch", "orphan_proof_hash", "proof_hash_mismatch", "schema_version", "symlink_escape", "unexpected_fairness", "unexpected_obligation_name", "unsafe_path", "unsafe_proof_path"]
}

def hasIssueCodeB (artifact : KernelSemanticsArtifact) (code : String) : Bool :=
  artifact.issueCodes.elem code

def hasProfileB (artifact : KernelSemanticsArtifact) (kind proofEngine : String) : Bool :=
  artifact.obligationProfiles.any (fun profile =>
    profile.kind == kind && profile.proofEngine == proofEngine)

def profileAdmissibilityB (artifact : KernelSemanticsArtifact) : Bool :=
  artifact.obligationProfiles.all (fun profile =>
    decide (profile.requiredObligations.length > 0))

def obligationCompletenessB (artifact : KernelSemanticsArtifact) : Bool :=
  hasProfileB artifact "safety_proof" "kinduction" &&
  hasProfileB artifact "safety_proof" "pdr" &&
  hasProfileB artifact "fair_liveness_proof" "pdr"

def pathSafetyEncodingB (artifact : KernelSemanticsArtifact) : Bool :=
  hasIssueCodeB artifact "unsafe_path" &&
  hasIssueCodeB artifact "unsafe_proof_path" &&
  hasIssueCodeB artifact "symlink_escape"

def hashMatchEncodingB (artifact : KernelSemanticsArtifact) : Bool :=
  hasIssueCodeB artifact "missing_bundle_hash" &&
  hasIssueCodeB artifact "missing_obligation_hash" &&
  hasIssueCodeB artifact "missing_proof_hash" &&
  hasIssueCodeB artifact "obligation_hash_mismatch" &&
  hasIssueCodeB artifact "proof_hash_mismatch" &&
  hasIssueCodeB artifact "bundle_hash_mismatch"

def smtStructuralSanityEncodingB (artifact : KernelSemanticsArtifact) : Bool :=
  hasIssueCodeB artifact "missing_assert" &&
  hasIssueCodeB artifact "check_sat_count" &&
  hasIssueCodeB artifact "exit_count" &&
  hasIssueCodeB artifact "invalid_command_order" &&
  hasIssueCodeB artifact "disallowed_commands"

def profileAdmissibility (artifact : KernelSemanticsArtifact) : Prop :=
  profileAdmissibilityB artifact = true

def obligationCompleteness (artifact : KernelSemanticsArtifact) : Prop :=
  obligationCompletenessB artifact = true

def pathSafetyEncoding (artifact : KernelSemanticsArtifact) : Prop :=
  pathSafetyEncodingB artifact = true

def hashMatchEncoding (artifact : KernelSemanticsArtifact) : Prop :=
  hashMatchEncodingB artifact = true

def smtStructuralSanityEncoding (artifact : KernelSemanticsArtifact) : Prop :=
  smtStructuralSanityEncodingB artifact = true

def kernelAccepts (artifact : KernelSemanticsArtifact) : Prop :=
  artifact.failClosed = true

def integrityPredicatesHold (artifact : KernelSemanticsArtifact) : Prop :=
  profileAdmissibility artifact ∧
  obligationCompleteness artifact ∧
  pathSafetyEncoding artifact ∧
  hashMatchEncoding artifact ∧
  smtStructuralSanityEncoding artifact

theorem profile_admissibility_holds : profileAdmissibility exported := by
  simp [profileAdmissibility, profileAdmissibilityB, exported]

theorem obligation_completeness_holds : obligationCompleteness exported := by
  simp [obligationCompleteness, obligationCompletenessB, hasProfileB, exported]

theorem path_safety_encoding_holds : pathSafetyEncoding exported := by
  simp [pathSafetyEncoding, pathSafetyEncodingB, hasIssueCodeB, exported]

theorem hash_match_encoding_holds : hashMatchEncoding exported := by
  simp [hashMatchEncoding, hashMatchEncodingB, hasIssueCodeB, exported]

theorem smt_structural_sanity_encoding_holds : smtStructuralSanityEncoding exported := by
  simp [smtStructuralSanityEncoding, smtStructuralSanityEncodingB, hasIssueCodeB, exported]

theorem kernel_accepts_implies_integrity_predicates_hold :
    kernelAccepts exported -> integrityPredicatesHold exported := by
  intro _
  exact ⟨
    profile_admissibility_holds,
    obligation_completeness_holds,
    path_safety_encoding_holds,
    hash_match_encoding_holds,
    smt_structural_sanity_encoding_holds
  ⟩

def counterexampleMissingPathCode : KernelSemanticsArtifact :=
  { exported with issueCodes := exported.issueCodes.filter (fun code => code != "unsafe_path") }

theorem counterexample_missing_path_code_breaks_path_safety :
    ¬ pathSafetyEncoding counterexampleMissingPathCode := by
  simp [pathSafetyEncoding, pathSafetyEncodingB, hasIssueCodeB,
    counterexampleMissingPathCode, exported]

end TarsierKernelSemanticsV1
