(* Auto-generated by .github/scripts/export_kernel_semantics_coq.py.
   Do not edit manually; regenerate from kernel_semantics_v1.json. *)
From Coq Require Import String List Bool Arith.
Import ListNotations.
Open Scope string_scope.

Module TarsierKernelSemanticsV1.

Record obligation_profile := {
  kind : string;
  proof_engine : string;
  required_obligations : list string;
  requires_induction_k : bool;
  fairness : option (list string);
}.

Record governance_profile := {
  name : string;
  min_solvers : nat;
  require_proofs : bool;
  require_proof_checker : bool;
  require_foundational_proof_path : bool;
}.

Record kernel_semantics_artifact := {
  schema_version : nat;
  certificate_schema_version : nat;
  certificate_hash_domain_tag : string;
  fail_closed : bool;
  obligation_profiles : list obligation_profile;
  governance_profiles : list governance_profile;
  issue_codes : list string;
}.

Definition exported : kernel_semantics_artifact :=
  {|
    schema_version := 1;
    certificate_schema_version := 2;
    certificate_hash_domain_tag := "tarsier-certificate-v2\n";
    fail_closed := true;
    obligation_profiles := [
    {|
      kind := "safety_proof";
      proof_engine := "kinduction";
      required_obligations := ["base_case"; "inductive_step"];
      requires_induction_k := true;
      fairness := None;
    |};
    {|
      kind := "safety_proof";
      proof_engine := "pdr";
      required_obligations := ["init_implies_inv"; "inv_and_transition_implies_inv_prime"; "inv_implies_safe"];
      requires_induction_k := true;
      fairness := None;
    |};
    {|
      kind := "fair_liveness_proof";
      proof_engine := "pdr";
      required_obligations := ["init_implies_inv"; "inv_and_transition_implies_inv_prime"; "inv_implies_no_fair_bad"];
      requires_induction_k := true;
      fairness := Some ["weak"; "strong"];
    |};
  ];
    governance_profiles := [
    {|
      name := "standard";
      min_solvers := 1;
      require_proofs := false;
      require_proof_checker := false;
      require_foundational_proof_path := false;
    |};
    {|
      name := "reinforced";
      min_solvers := 2;
      require_proofs := true;
      require_proof_checker := false;
      require_foundational_proof_path := false;
    |};
    {|
      name := "high-assurance";
      min_solvers := 2;
      require_proofs := true;
      require_proof_checker := true;
      require_foundational_proof_path := true;
    |};
  ];
    issue_codes := ["bundle_hash_mismatch"; "check_sat_count"; "disallowed_commands"; "duplicate_obligation_file"; "duplicate_obligation_name"; "empty_obligations"; "exit_count"; "invalid_command_order"; "invalid_expected"; "invalid_expected_for_proof"; "invalid_kind"; "invalid_obligation_extension"; "invalid_proof_engine"; "missing_assert"; "missing_bundle_hash"; "missing_file"; "missing_induction_k"; "missing_obligation_hash"; "missing_or_invalid_fairness"; "missing_proof_file"; "missing_proof_hash"; "missing_required_obligation"; "obligation_hash_mismatch"; "orphan_proof_hash"; "proof_hash_mismatch"; "schema_version"; "symlink_escape"; "unexpected_fairness"; "unexpected_obligation_name"; "unsafe_path"; "unsafe_proof_path"];
  |}.

Definition has_issue_codeb (artifact : kernel_semantics_artifact) (code : string) : bool :=
  existsb (String.eqb code) artifact.(issue_codes).

Definition has_profileb
  (artifact : kernel_semantics_artifact)
  (target_kind target_engine : string) : bool :=
  existsb (fun profile =>
    andb (String.eqb profile.(kind) target_kind)
         (String.eqb profile.(proof_engine) target_engine))
    artifact.(obligation_profiles).

Definition profile_admissibilityb (artifact : kernel_semantics_artifact) : bool :=
  forallb (fun profile =>
    Nat.ltb 0 (List.length profile.(required_obligations)))
    artifact.(obligation_profiles).

Definition obligation_completenessb (artifact : kernel_semantics_artifact) : bool :=
  andb (has_profileb artifact "safety_proof" "kinduction")
    (andb (has_profileb artifact "safety_proof" "pdr")
          (has_profileb artifact "fair_liveness_proof" "pdr")).

Definition path_safety_encodingb (artifact : kernel_semantics_artifact) : bool :=
  andb (has_issue_codeb artifact "unsafe_path")
    (andb (has_issue_codeb artifact "unsafe_proof_path")
          (has_issue_codeb artifact "symlink_escape")).

Definition hash_match_encodingb (artifact : kernel_semantics_artifact) : bool :=
  andb (has_issue_codeb artifact "missing_bundle_hash")
    (andb (has_issue_codeb artifact "missing_obligation_hash")
      (andb (has_issue_codeb artifact "missing_proof_hash")
        (andb (has_issue_codeb artifact "obligation_hash_mismatch")
          (andb (has_issue_codeb artifact "proof_hash_mismatch")
                (has_issue_codeb artifact "bundle_hash_mismatch"))))).

Definition smt_structural_sanity_encodingb (artifact : kernel_semantics_artifact) : bool :=
  andb (has_issue_codeb artifact "missing_assert")
    (andb (has_issue_codeb artifact "check_sat_count")
      (andb (has_issue_codeb artifact "exit_count")
        (andb (has_issue_codeb artifact "invalid_command_order")
              (has_issue_codeb artifact "disallowed_commands")))).

Definition profile_admissibility (artifact : kernel_semantics_artifact) : Prop :=
  profile_admissibilityb artifact = true.

Definition obligation_completeness (artifact : kernel_semantics_artifact) : Prop :=
  obligation_completenessb artifact = true.

Definition path_safety_encoding (artifact : kernel_semantics_artifact) : Prop :=
  path_safety_encodingb artifact = true.

Definition hash_match_encoding (artifact : kernel_semantics_artifact) : Prop :=
  hash_match_encodingb artifact = true.

Definition smt_structural_sanity_encoding (artifact : kernel_semantics_artifact) : Prop :=
  smt_structural_sanity_encodingb artifact = true.

Definition kernel_accepts (artifact : kernel_semantics_artifact) : Prop :=
  artifact.(fail_closed) = true.

Definition integrity_predicates_hold (artifact : kernel_semantics_artifact) : Prop :=
  profile_admissibility artifact /\
  obligation_completeness artifact /\
  path_safety_encoding artifact /\
  hash_match_encoding artifact /\
  smt_structural_sanity_encoding artifact.

Lemma profile_admissibility_holds : profile_admissibility exported.
Proof. vm_compute. reflexivity. Qed.

Lemma obligation_completeness_holds : obligation_completeness exported.
Proof. vm_compute. reflexivity. Qed.

Lemma path_safety_encoding_holds : path_safety_encoding exported.
Proof. vm_compute. reflexivity. Qed.

Lemma hash_match_encoding_holds : hash_match_encoding exported.
Proof. vm_compute. reflexivity. Qed.

Lemma smt_structural_sanity_encoding_holds : smt_structural_sanity_encoding exported.
Proof. vm_compute. reflexivity. Qed.

Theorem kernel_accepts_implies_integrity_predicates_hold :
  kernel_accepts exported -> integrity_predicates_hold exported.
Proof.
  intro _.
  exact (conj profile_admissibility_holds
    (conj obligation_completeness_holds
      (conj path_safety_encoding_holds
        (conj hash_match_encoding_holds
          smt_structural_sanity_encoding_holds)))).
Qed.

Definition counterexample_missing_path_code : kernel_semantics_artifact :=
  {|
    schema_version := exported.(schema_version);
    certificate_schema_version := exported.(certificate_schema_version);
    certificate_hash_domain_tag := exported.(certificate_hash_domain_tag);
    fail_closed := exported.(fail_closed);
    obligation_profiles := exported.(obligation_profiles);
    governance_profiles := exported.(governance_profiles);
    issue_codes := List.filter
      (fun code => negb (String.eqb code "unsafe_path"))
      exported.(issue_codes);
  |}.

Lemma counterexample_missing_path_code_breaks_path_safety :
  ~ path_safety_encoding counterexample_missing_path_code.
Proof.
  vm_compute.
  discriminate.
Qed.

End TarsierKernelSemanticsV1.
